cd Documents
mkdir ma20240469-iz
cd ma20240469-iz
code . 

FROM node:20-slim
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
CMD ["npm", "run", "dev"]

cd backend
docker build -t ma20240469-backend .
docker images

docker run -d -p 6001:5000 --name ma20240469-provera ma20240469-backend
docker ps
docker logs ma20240469-provera
curl http://localhost:6001/health

echo "BACKEND IMAGE" >> ma20240469-backend.txt
docker images ma20240469-backend >> ma20240469-backend.txt

echo "BACKEND CONTAINER" >> ma20240469-backend.txt
docker ps -f name=ma20240469-provera >> ma20240469-backend.txt

echo "BACKEND LOGS" >> ma20240469-backend.txt
docker logs ma20240469-provera >> ma20240469-backend.txt

echo "BACKEND HEALTH" >> ma20240469-backend.txt
curl http://localhost:6001/health >> ma20240469-backend.txt

Standardni PostgreSQL/NODE.JS

name: ma20240469-app

services:
  database:
    image: postgres:16-alpine
    container_name: ma20240469-db
    env_file:
      - env/backend.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d reservations"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - ma20240469-network

  backend:
    image: ma20240469-backend
    container_name: ma20240469-back
    env_file:
      - env/backend.env
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ma20240469-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ma20240469-front
    env_file:
      - env/frontend.env
    ports:
      - "7000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - ma20240469-network

networks:
  ma20240469-network:
    name: ma20240469-network

volumes:
  postgres-data:
    name: postgres-data

docker compose up -d

echo "IMAGES" >> ma20240469.txt
docker images >> ma20240469.txt

echo "CONTAINERS" >> ma20240469.txt
docker ps -a >> ma20240469.txt

echo "VOLUMES" >> ma20240469.txt
docker volume ls >> ma20240469.txt

echo "NETWORKS" >> ma20240469.txt
docker network ls >> ma20240469.txt

echo "COMPOSE" >> ma20240469.txt
docker compose ps >> ma20240469.txt

-----------------------------------------------
MySQL 8.0 & Python setup/PYTHON

FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]

sudo docker build -t ma20240469-backend .
sudo docker images

sudo docker run -d -p 4001:5000 --name ma20240469-test ma20240469-backend
sudo docker ps
sudo docker logs ma20240469-test
curl http://localhost:4001/health

echo "BACKEND IMAGE" >> ma20240469-backend.txt
docker images ma20240469-backend >> ma20240469-backend.txt

echo "BACKEND CONTAINER" >> ma20240469-backend.txt
docker ps -f name=ma20240469-test >> ma20240469-backend.txt

echo "BACKEND LOGS" >> ma20240469-backend.txt
docker logs ma20240469-test >> ma20240469-backend.txt

echo "BACKEND HEALTH" >> ma20240469-backend.txt
curl http://localhost:4001/health >> ma20240469-backend.txt


name: ma20240469-app

services:
  database:
    image: mysql:8.0
    container_name: ma20240469-db
    env_file:
      - env/backend.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "student", "--password=student"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - ma20240469-network

  backend:
    image: ma20240469-backend
    container_name: ma20240469-back
    env_file:
      - env/backend.env
    ports:
      - "5000:5000"
    volumes:
      - /app/__pycache__
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ma20240469-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ma20240469-front
    env_file:
      - env/frontend.env
    ports:
      - "7000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - ma20240469-network

networks:
  ma20240469-network:
    name: ma20240469-network

volumes:
  mysql-data:
    name: mysql-data

docker compose up -d

echo "IMAGES" >> ma20240469.txt
docker images >> ma20240469.txt

echo "CONTAINERS" >> ma20240469.txt
docker ps >> ma20240469.txt

echo "VOLUMES" >> ma20240469.txt
docker volume ls >> ma20240469.txt

echo "NETWORKS" >> ma20240469.txt
docker network ls >> ma20240469.txt

echo "COMPOSE" >> ma20240469.txt
docker compose ps >> ma20240469.txt
-----------------------------------------------------------------------------

name: ma20240469-jul

services:
  backend:
    image: backend-image-z2
    container_name: ma20240469-server
    env_file:
      - env/backend.env
    ports:
      - "7000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    networks:
      - ma20240469-mreza
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ma20240469-app
    env_file:
      - env/frontend.env
    ports:
      - "3000:3000"  # Mapira lokalni port 3000 na port kontejnera
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - ma20240469-mreza
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    container_name: ma20240469-baza
    env_file:
      - env/database.env
    volumes:
      - ma20240469-postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d games"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - ma20240469-mreza

volumes:
  ma20240469-postgres-data:

networks:
  ma20240469-mreza:
    driver: bridge
